# Generated by Django 3.1.2 on 2021-02-05 16:48

from django.db import migrations, models
import tyadmin_api_cli.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='嘉宾姓名')),
                ('avatar', tyadmin_api_cli.fields.SImageField(max_length=255, upload_to='vipguest_avatar', verbose_name='嘉宾头像')),
                ('job', models.CharField(max_length=255, verbose_name='嘉宾职业')),
                ('introduction', models.CharField(max_length=255, verbose_name='个人介绍')),
            ],
            options={
                'verbose_name': '嘉宾',
                'verbose_name_plural': '嘉宾',
            },
        ),
    ]
