# Generated by Django 3.1.2 on 2021-02-20 09:50

from django.db import migrations, models
import tyadmin_api_cli.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_auto_20210205_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='评委姓名')),
                ('avatar', tyadmin_api_cli.fields.SImageField(max_length=255, upload_to='vipguest_avatar', verbose_name='评委头像')),
                ('job', models.CharField(max_length=255, verbose_name='评委职业')),
                ('introduction', models.TextField(verbose_name='评委介绍')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '评委',
                'verbose_name_plural': '评委',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='机构名称')),
                ('avatar', tyadmin_api_cli.fields.SImageField(max_length=255, upload_to='vipguest_avatar', verbose_name='机构图标')),
                ('service', models.CharField(max_length=255, verbose_name='机构业务')),
                ('introduction', models.TextField(verbose_name='机构介绍')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.AddField(
            model_name='vipguest',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='可见'),
        ),
        migrations.AddField(
            model_name='vipguest',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
