# Generated by Django 3.1.2 on 2021-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_auto_20210220_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=255, verbose_name='活动id')),
                ('type', models.CharField(max_length=255, verbose_name='分类名称')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('content', models.TextField(max_length=255, verbose_name='活动内容')),
                ('dtime', models.DateField(verbose_name='活动日期')),
                ('stime', models.DateTimeField(verbose_name='开始时间')),
                ('etime', models.DateTimeField(verbose_name='结束时间')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '时间线',
                'verbose_name_plural': '时间线',
            },
        ),
    ]
