# Generated by Django 3.1.2 on 2021-02-20 11:21

from django.db import migrations, models
import tyadmin_api_cli.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_tasktimeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktimeline',
            old_name='type',
            new_name='tasktype',
        ),
        migrations.AddField(
            model_name='organization',
            name='orgtype',
            field=models.CharField(choices=[('director', '指导单位'), ('sponsor', '主办单位'), ('agency', '承办单位'), ('supporter', '支持单位')], default='sponsor', max_length=255, verbose_name='机构类型'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='avatar',
            field=tyadmin_api_cli.fields.SImageField(max_length=255, upload_to='judge_avatar', verbose_name='评委头像'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=tyadmin_api_cli.fields.SImageField(max_length=255, upload_to='org_avatar', verbose_name='机构图标'),
        ),
    ]
