# Generated by Django 3.1.2 on 2021-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_auto_20210220_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='orgurl',
            field=models.CharField(default='', max_length=255, verbose_name='机构链接'),
        ),
    ]
