# Generated by Django 3.1.2 on 2021-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_organization_orgurl'),
    ]

    operations = [
         migrations.AlterField(
            model_name='organization',
            name='orgtype',
            field=models.CharField(choices=[('director', '指导单位'), ('sponsor', '主办单位'), ('agency', '承办单位'), ('donator', '赞助单位'), ('strategy', '战略合作单位'), ('supporter', '支持单位')], default='sponsor', max_length=255, verbose_name='机构类型'),
        )
    ]
