# Generated by Django 3.1.2 on 2021-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_auto_20210412_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='mail',
            field=models.EmailField(max_length=255, verbose_name='邮箱'),
        ),
    ]
