# Generated by Django 3.1.2 on 2021-05-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_auto_20210412_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0, verbose_name='轮次')),
                ('innovation', models.IntegerField(default=0, verbose_name='创新性')),
                ('commercial', models.IntegerField(default=0, verbose_name='商业性')),
                ('competitiveness', models.IntegerField(default=0, verbose_name='竞争力')),
                ('team', models.IntegerField(default=0, verbose_name='团队情况')),
                ('public_benefit', models.IntegerField(default=0, verbose_name='社会收益')),
                ('sum', models.IntegerField(default=0, verbose_name='总分')),
                ('comment', models.TextField(verbose_name='点评')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_api.judge', verbose_name='评委')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_api.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
    ]
