# Generated by Django 3.1.2 on 2021-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0014_wxuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='edu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='enroll',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='入学年份'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='grad',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='毕业年份'),
        ),
    ]
