# Generated by Django 3.1.2 on 2021-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0016_auto_20211110_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='USER_BIRTH',
            field=models.IntegerField(default=0, verbose_name='出生年月'),
        ),
    ]
