# Generated by Django 3.1.2 on 2021-11-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0017_auto_20211110_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wxuser',
            old_name='userid',
            new_name='USER_ID',
        ),
    ]
