# Generated by Django 3.1.2 on 2021-11-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0018_auto_20211110_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN_ID', models.CharField(max_length=255, verbose_name='用户id')),
                ('ADMIN_NAME', models.CharField(max_length=255, verbose_name='姓名')),
                ('ADMIN_PHONE', models.CharField(max_length=255, verbose_name='电话')),
                ('ADMIN_STATUS', models.IntegerField(default=0, verbose_name='状态')),
                ('ADMIN_LOGIN_CNT', models.IntegerField(default=0, verbose_name='登录次数')),
                ('ADMIN_LOGIN_TIME', models.IntegerField(default=0, verbose_name='登录时间')),
                ('ADMIN_TYPE', models.IntegerField(default=0, verbose_name='类型')),
                ('ADMIN_TOKEN', models.CharField(max_length=255, verbose_name='token')),
                ('ADMIN_TOKEN_TIME', models.CharField(max_length=255, verbose_name='token时间')),
                ('ADMIN_ADD_TIME', models.IntegerField(default=0, verbose_name='添加时间')),
                ('ADMIN_ADD_IP', models.CharField(blank=True, max_length=255, null=True, verbose_name='添加IP')),
                ('ADMIN_EDIT_TIME', models.IntegerField(default=0, verbose_name='修改时间')),
                ('ADMIN_EDIT_IP', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改IP')),
            ],
            options={
                'verbose_name': '小程序管理员',
                'verbose_name_plural': '小程序管理员',
            },
        ),
    ]
